---
title: 'DS Sir Practical'
author: "Debjit Khaskel"
date: "2024-11-06"
output: word_document
---

```{r}
library(tidyverse)
AirPassengers
ap=as.vector(AirPassengers)
time=seq(1:length(ap))
ap_data=data.frame(time,ap)
ap_data
```

```{r}
ggplot(data = ap_data,mapping = aes(x=time,y=ap))+
  geom_point()+
  geom_line()+
  geom_smooth()+
  labs(title = "Yearly Air Passengers")+
  xlab("Time")+
  ylab("Air Passengers")
```
```{r}
HairEyeColor
```

```{r}
HairEyeColor
hr=HairEyeColor
males=data.frame(hr[,2,1])
males_new=data.frame(color=row.names(males),number=males[,1])
ggplot(data=males_new,aes(x=number,y=color))+
  geom_bar(stat = 'identity',fill='blue')
```
```{r}
males_hec=data.frame(hr[,,1])
ggplot(data=males_hec,mapping = aes(fill=Eye, x=Hair, y=Freq))+
  geom_bar(stat = "identity",position="dodge")
```

```{r}
ggplot(data=males_hec,mapping = aes(fill=Eye, x=Hair, y=Freq))+
  geom_bar(stat = "identity",position="fill")
```

```{r}
ggplot(data=males_hec,mapping = aes(fill=Eye, x=Hair, y=Freq))+
  geom_bar(stat = "identity",position='fill')+
  coord_polar(theta = "y")
```
```{r}
ggplot(data=males_hec,mapping = aes(fill=Eye, x='', y=Freq))+
  geom_bar(stat = "identity",position='fill')+
  coord_polar(theta = "y")+
  facet_wrap(~Hair, ncol = 3,scales = 'free')
```

```{r}
library(MASS)
attach(Cars93)
names(Cars93)
hp=Cars93$Horsepower
pr=Cars93$Price
biv=data.frame(Horsepower=hp,Price=pr)
biv
```
```{r warning=FALSE}
library(tidyverse)
ggplot(biv,aes(x=Horsepower,y=Price))+
  geom_point()
```
In the lower range it shows a linear relationship but as we increase the horsepower we see that the assosiation is weak.
```{r}
cor(hp,pr)
```
There exists a strong positive linear association between horsepower and price.
```{r}
fit.line=lm(pr~hp)
coef=as.vector(coefficients(fit.line))
a.hat=coef[1]
b.hat=coef[2]
fit.pr=predict(fit.line);fit.pr
res=resid(fit.line)
```

```{r}
plot=ggplot(biv,aes(x=Horsepower,y=Price))+
  geom_point()+
  geom_abline(aes(intercept=a.hat,slope=b.hat))
```

```{r}
lin_reg=data.frame(biv,Y=fit.pr,e=res);lin_reg
res_plot=ggplot(lin_reg,aes(x=Horsepower,y=e))+
  geom_point()

cor(res,hp)
```


```{r}
install.packages("gridExtra")
library(gridExtra)
```
```{r}
grid.arrange(plot,res_plot,nrow=2)
